//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppЛРОПБД.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int id_service { get; set; }
        public Nullable<int> id_klient { get; set; }
        public Nullable<int> id_provider { get; set; }
        public Nullable<int> id_PriceList { get; set; }
        public Nullable<int> ConnectingTime { get; set; }
        public Nullable<decimal> Result { get; set; }
    
        public virtual Klient Klient { get; set; }
        public virtual PriceList PriceList { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
